language: node_js
sudo: required
dist: trusty
node_js:
  - "8.11.3"

addons:
  apt:
    update: true
    packages:
    - curl
    - fonts-liberation
    - libappindicator1
    - google-chrome-stable

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start